name: Feature Request
description: Suggest a new feature for OPNet Node
title: "[Feature]: "
labels: ["enhancement", "triage"]
body:
  - type: markdown
    attributes:
      value: |
        Thanks for suggesting a feature for OPNet Node.

        Please note that features affecting consensus require extensive review and testing.

  - type: textarea
    id: description
    attributes:
      label: Feature Description
      description: A clear and concise description of the feature you'd like.
      placeholder: Describe the feature...
    validations:
      required: true

  - type: textarea
    id: problem
    attributes:
      label: Problem Statement
      description: What problem does this feature solve? What use case does it address?
      placeholder: I'm always frustrated when...
    validations:
      required: true

  - type: textarea
    id: solution
    attributes:
      label: Proposed Solution
      description: How do you envision this feature working?
      placeholder: Describe your ideal solution...
    validations:
      required: true

  - type: textarea
    id: alternatives
    attributes:
      label: Alternatives Considered
      description: Have you considered any alternative solutions or workarounds?
      placeholder: I've also considered...

  - type: dropdown
    id: impact
    attributes:
      label: Consensus Impact
      description: Does this feature affect consensus behavior?
      options:
        - "No - UI/UX or tooling only"
        - "No - Internal optimization only"
        - "Potentially - Needs review"
        - "Yes - Changes state calculation"
        - "Yes - Changes validation rules"
    validations:
      required: true

  - type: checkboxes
    id: terms
    attributes:
      label: Checklist
      options:
        - label: I have searched existing issues to ensure this feature hasn't been requested
          required: true
        - label: I understand that consensus-affecting features require extensive review
          required: true
